### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by EliabCuicas** [imunes/imunes-examples#1]
Hello, I'm working with IMUNES and it's really annoying that you can't save the configuration of the computers in a simple way. That's why I'm studying the scripts of these examples to automate the configuration process in different topologies. My question is if there is any reference manual or a document where I can guide me to better understand the scripts of these examples and apply them in the future? thank you.

**Comment by denisSal** [comment]
http://imunes.net/download

There is a PDF and an HTML under `IMUNES Manual`. Check it out, and if you are still not able to do what you want, write exactly what you are trying to do and I'll try to help.

Cheers,
Denis

**Comment by EliabCuicas** [comment]
Hello Denis, me again, I had not seen your message, a professor at the university was given the task of translating chapter 5 of the IMUNES manual into Spanish, there is the advanced configuration section, I'll leave it posted. To help those who want to review it in Spanish
[Manual Imunes cap.5 Uso avanzado.pdf](https://github.com/imunes/imunes-examples/files/2926692/Manual.Imunes.cap.5.Uso.avanzado.pdf)

**Comment by denisSal** [comment]
Thank you very much! If you translate the whole document, let me know so I can put it on the official IMUNES documentation.
